title: AI Methods for Materials Science
author: Rodrigo A. Vargas-Hernandez
logo: course_logo.png
execute:
  execute_notebooks: auto
  timeout: 90
parse:
  myst_enable_extensions:
    - colon_fence
    - deflist
    - dollarmath
    - linkify
    - substitution
html:
  use_repository_button: false
  use_issues_button: false
  use_multitoc_numbering: true

